database:
  host: 192.168.77.109
  port: 3306
  user: root
  password: marugame
  database_name: pcb_inspection_db

syslog_server:
  ip_addr: 192.168.77.109
  service_name: pcb_inspection_database

socket:
  socket_path: /tmp/database_server.sock
#  database_path: /run/mysqld/mysqld.sock
